env:
  global:
    - secure: c+TQZXHpLTA5T8g1hk5kos6MkCj39aIM0vbcSUQfLChKxQvtEyVpUfrEq+/uf7eVWfRbv+y5Kpycu0pckzM3uk626TYycQacr0AQmlfHhMTUbLA0hb2rB95MQVrdNtwyHaY0/b+UVD45FQYs3nQUk/Di2UMj9WqMkMlMC4uy60y2EvT7PPhHIK2mJmDE0aAc0Zz3zJsowyIXXRSbICcATKvPNFfgdNWt/CqzvUENnU5PQMuj51p1l/UiKafBhmxAUXjA0ikjLfoZl7zrP6bH/j/G2bfVA0tkQAv3MjjWHm8MNn5gpDUudfoR0xYNq+Cxd5JCQB8HOVhs2wGlgvEH9NEw0fmrpqu/Zs3e/oksTrMGXdMfwJPd4IjgGPLhtCm/Rj1Waronvu548bwfyP9d+R43rl0FFFQgdFYGIFrIRQ4rBg/e+TSSKwMW9unr5klSs+OKXZkOLwP7gsnnQ0n6UxdhDXOyaA1unN+muYckS3YbOudCljnm1jHsguf54mZDPcgNg6Cz286aRSbIZYcRHK4Xx3exKCSHHTVAs0BPicwv9SQySZZXPjjC1pQWxxG85kpDKR++6ASefZd2Gqn1VrFFGAekSU2iIFICFFxwUNN0oCsd5d0WnOzJ23/wGkGqaUiNVPt0idUcLNlszr+SnEiKnkpXOkPByCDRVabQ2/A=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
