env:
  global:
    - secure: p7wbO0PA8jj9i/9Y4N5TJqJTPlUAhqfCfA1iUQ5ccnbu7wbznse3/fWx6OqsrM+VGc43og9sjMvC5EslSm7JBpldEzuZmuPQrMuBNQ2ygb+doh/4kswvGoptVEZCDvKN8FkHRSeOUXSstLCQwrnMMjhkkGGceHK3TzZyzoeDFAh3q6ScQawe/Amr/vHdaXFTeh57K/Wa+At1LrnzhFQ/8+nmyutbHsjplC3SxwoV+spidnojKK06xTLo+UHCZ5M7c+u848SDh1jYK8mEZkiCG+PmcySlnZ6YyXfklQxWbrRSpCWOsSYwdyrzcadtWWRhf/pwlDOgmmbRZMfRIdchvA7U8nbSKRv7yoS+owAVU1AIfRLWQSSTh7B1EBtvUezYvlqFssIneXH1d6+EBzwfMBgYJOI/u5DKLRfMW3V52bSRuSO567TWwe2MWQL5nyJPgjW/j5vh8nB+Xy9Q5NJFxQEWDUavgz6bLGYgVckLSH365lARwINNRGOGsA4yq23f0LeM00Q7qcZ3FNqrxfYYp0cXIT5JxKVdkMD0tDIxMv7bdyRK1rm8+qrj1dLqB3/gskte9ph0CcXYa5IvCyT76Pfj5xWli29gVwGOb6+E6t/DTiBpJWj0gq2Edfzol3QxKlgC3E53OS6dEbrFsxzmj7Ptv8UTLkN+dcgvGTmCA6M=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
