env:
  global:
    - secure: sxDs+PnunjjWUqqQU991998pvP9JA6uRLEFqM2GqTP5i/Gaw5Vr+iMS0Zl27FREwrzlWLdPmaaa2ao06hBSqDmy9EVl8YOnEvNK4a0vQZI6E7JZIscRx+iwGaD6Qpn8f/0VeTrtnYnYKf1jqSLU6cl5hdJQC1zVHdR4HMep1B2BLJPztO9RkOPtZRcqpAYdBqkf8wXo2XLa+GHMWgpXoNRxaFfj0Gf7ylenZpl8WzXGPwBM75LlDpl5LuvlR2OuIed6Bfsv2Y2v5BFTQYez9v9oHPfzIzn6GvrpOUiKw6mzxfx4qpTaCaay7v0/kZR6h7LBAp0wHUYBJ/WMuZxU2sFsi9exQDu69DRTfotTxxg5DBc8l4BGCpIqgQQzJrnLk7D1QY/vxYSWYe6ZZF7iiCUDMhMW+dZOFMnQja/uKV6NRF4jZsCDXTNZSAVsMEcPzV/oT4Opp/PfHBbVx8EHZ3WBJW2g3qBhxolFZ0qgONccTqX/kqsh3VSia2wRNqRPb6rqz2b2xlqO23r83rNVUuq99QMPq21DtCW8CUddLsXYaINGcwJQMloneqIhCrbOEQt67R1Wugi/SkrJ0aqpsRQJkcOLLpyImsyBZswcNoO0dtU3Bliv+CVIV8b0yhnDumM1i+fPA/t7jamWg6U/fkZAU1SlYxCuhqcDv4PZx0kE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
