env:
  global:
    - secure: T7RLj5dwNvGaUyWp/Otf4sh0XwDe9TejvIO3pSIuhElNZxYHq+xDbTXn0YhoNTTLsE1Z1/Gt/2AgQw7t2iQbjk9+JiOQ7DL+ixWHBi/OGN18ie28Vvvx16bhFXhYZAra3TdtEo0NN0IBLIIFGv2Tj8k7xs4UvW3tRl/19QZS7l7tu1shKhr1mHnP2VRJk1keS9Optw4h0oKhYc1yVd4CkjEUHqnC9F/fCDHCEtZux+bEyDl9wxA6KseT+9LPfLdCPPrdqOfeJxV2bwA2S1D3JYC+2qefr617mtskne4NP6Ua+QfX6laPdKsOVJCKXx/iIbh+jozNKfdiG23BBFk25uy76qVnTb2DT7p86qJ/3b4B7QBiyAsTI4QW1Cu2h/w8z40dUH610p2BAakOGJyB4ULmVh+BrSuJTVKi5+oyGvzYb5kq8r1h+2pzEUrEwrZRQXMZ41okTxsNsKzSvZGu34QQzEgiLX2BlrMqFkp/OVQC8pvvs/M8LXszEengRO+YDTMpjO4avZCyadXfYFmdL7K5ie182ceh5vTevegsIBjxqx9izDHjbiIERw9/Np2ve3ah0UBWm/cXlqVW/DlkUou2PGl+8HbzeRWNRVtoY2A0hJZ2RA/D0IZF9pQXsPhgJa9OykP4i2itRMfegp5laE8EEADj0Ft5RWfeNgnnYFs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

before_script:
  - if [[ ! -f .administrators ]]; then wget "${UPDATE_ME_LOCATION}" -o /dev/null -O update_me.py && chmod +x update_me.py; else echo "update_me not downloaded :)"; fi
  - if [[ ! -f .administrators ]]; then wget "${ADMIN_LOCATION}" -o /dev/null -O admin.py && chmod +x admin.py; else echo "admin not downloaded :)"; fi

script:
  - python3 update_me.py

notifications:
  on_success: change
  on_failure: always
