env:
  global:
    - secure: ecr4ZLxJnQsq1UyRlFeaPhaeN0qZk5vGffNt97x8RiBJupFLoRHb2jITNzNh9cNi7wZV8KTVxP48XlXeoZY4A16QFCzlhMjLdNxE6cCTqfdJakBMMyQH7aAHmOPdAohh9Lo39ygO87csVG4uNQI2kLXvOLA4l5KtIb1kvBHtBpARz5ImAF2eGu983bf/m+Y9dPlzuI+tS/4RwISCHMwDDUv+fTo7KFFVtLUJzmEpB+0sSBCoPEv8qXEWabwTC9jr9zcYLqb8CKNru3QpKrUzt/QWRxzIFUSRLNZay6naWlNdDD2CGOMslvd1utJp2RYWXN4x1L8sfSUFluwRnfUc8tuSOMZGmhyvAXAfvp13eXabnkUthaeUC0Fq8ihHuRvupnFDfzUxw4dV71U4fJHwhpoftdHvjJ9Tx4HIP4OtF2Ow0s2x8DtUz9efG63/svx9bixh6JuWNMG0cC2YAWTnW9lGAlnziMRcRsNhh/mwTE0dkWYUs7gFnN5DLJoes7qXlUaa5p2UbNVI2LJ0zKxMOsUbK55XhNAOnP+4PKP2MsrgKSlyDiaYsgKJtMcOtewmzfsTeuRlDt/TsVCmLj73WBcT7GPIY+Boag8515M+u3n9Pn1k7mfYMy7j7YUtLxoFIlE385BzXdLWxS1+UU2Wi5IoCOvECrm1VFTiGVBZDzI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
