env:
  global:
    - secure: MGZNgktT/7eX198Uj69+200v/BN8nuteMojENBTPt7sHSWVtyp33CzI+0HAvmxZYEWq/ZzfWh5f+HvDfnk68oIHqjFIAj9L1ILRJaAXSdavPngYeHSARCOSghA042JDRDDnejJUDDEbVKrkKWYtJ9uaIRNg/Q4Sx8imOCrYM1sh0Rz2PGVaneYAaTO+6dVID3MrqN2i0hiDnlfxutbZFaJzN2+8wn2Ze+xmh6A/ir3NRxhscY5VQwiElgpiSzh9H+N/wKWIUTMDf45luAXvSJbEowhzKKIhfE/JjIYGfvErtJeZalAriQIWnx/AoDN4mm+r9hexaeQtBdNMhj6bzW/YA56QGoaKI67d/baQzUABRhKiYZnd8xPOqIA8HgeB7T743W7EvTfKdFG+hPXp0IML8nFkycD0HlXpPS3RdgeKPl2SOy3beQA3/Rnctr3jmlFAM0VkQoIdL9hITVS/Yyjp1/d7g/QIzAxwU934YDz8WPSPISfaIOFfPbyuJwvybmjsPcHJlfQagbBYC0pTWaHHL7ZQP9nLEQ31X5BzHKPlLVpzPb5qKWbV1LWRohtEbWZZWMDS+U8o4jO3gu4FFWCHQde54iE4v/foHATSBd0oRLqIYZ/opHK2wdcP0q40/1Zqa8trH3m6fY51NOhBLAqQdxq5Gr1VML+UAdMpiyEg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
