env:
  global:
    - secure: jQqdrc0hRUjQ5GEaAYQsW0OhjznnCi1KguMoodUNZ8ZYiKQEMOV1agVspqPKKLLWPYizwqpBGsO9WAeAxV4UUUpQkkJ++YIibffrno3QQteKfDQR9Kt1iBM/uOAOc9fZZuRrShCyPK7OW3OWkTWdOuV20AyUTq0q8ibtv8KntgLhr1335pPCYf7wsNxaVhBuYV50ynTgbHMWgyD/bsVd5RGmgN6E/Qn6G40mnemEYcGMKbSVxJS8yMRlP8UFhbvB3If+wkN2ameQ2yO45ZqjjCTOAd4WoC3+dBHV+vE7Shio6ONLV6wDI23UPRpbs4JMLCrOEBkC2x1T/AN667JdPK9TtmBxr+yPsZuO8MpvXsxZHQKD6xREcAjQAwdtH5G7A9FKGDhuwh1/keqT2+ssWB3ceSsjvJfGjNimY5JTKzyzo5H4nRmpgx/zD91TbxA5JujVcleKN4cv38AF9caTwHh5v0JKgCrs5MYZENcULsvfPrahF8hjhO1G7KPeqClg+eOaQ2HeI6bKYOA4ql8IZQhk/SuryFQtAosOFlgjlKTjg42en6Vm3DItU8a4on/TEUIgJvR7cnXXcatGOYqKDLNW0ujNTIgtYty488Ne+Y82XcWUTAsh6Qs2KL287fY4cheWFZQPeoa4N707mTYWJkLOiBDJDARiLRzaxUkzZk8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
