env:
  global:
    - secure: m4x8ujjQ4llZdiMafS7fbLFPiNC/GxLFW0FmCVo2mE351a3t53T7V/YYPceseq2ggXTbMQ9SIbmlbjjPJydmTrBUSPSU7C0X09mR/OzSUrTJyrZoI4cFlabzW6D0ub599FR/AI+adQ6xq13R1145We58CenaBycBUuknE4n0f3DdRAXsSor7Jnp+G5aMYuRdTDZQpQwm4ulqjVF5JQHk2cMLREMdpmP+BImuAM0jZLGGQMn993Kg8dSfiGQZ/W1tgacBNp16HEIaTfyRPEUU5X+K9WL6KwvdX6WbCs9/1h4E1R+Lam2c5IvErOUeDoL7e0aNG5BeiR4sY+k6qV9ZQnDAbPa29M3vhaSMtOtehay7aWZEceStVaQPF2mG1pHVvScExY1xbGXkwZT7JtyMQBYy4Bd07I66wyRoknF0C/X3oeIMfkHL7aLw077yoMCUYOr3YwfysYC/4F/CnbKbf0VswAP1Wv92+kjZUMSCIH5bKCRlrljIPYJOVQXl/Gj/ISwOU2Ywsl8EeXeFYJuIdSdtRkyt0q6T/X6LVcB2bptAJFh2xUAn8cySrYlsSkMqTADYJF3x3qU3z0R1DWxnKP1qj4GKnGoBm0UuHet+m26U6+0P28OFVlDOWhVp12tuIXDWWazZ9tbiynJusxqKD27mTR9GRSqmQ6OFdRfgV5Q=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
