env:
  global:
    - secure: RXgSIgri2C0r4c8BysP1VW1R2ux/5z18ViOTv0AX5DPn1pvykIJpAYcbqKEH5HfSfFltAXkZMMlP5o2MRCL3uGgYctY5YpH30+H8KOkT4EpP+u6E/JMFI1VTo6TyV36UYeN8RQjzmivK1V8hZ+NOrxV85prmhMn9EWdJbGfQ8N2R2KAnYPaMBauBmesCd/Usr3EvqMe9EYl3C6IzOYa/IwTmNtZsd+WeP4H00vrwB4or5ABVJIbsfLHbgsHlv5VXSwqQinRyZre1cgC6tA4B8DypZCn2cT4cSlqiW9pltD6/UIWq8yMiIrAwDQ2d8I8TI4CtZRgvFoihyE3715RvBpsLZHvr3sh0L+bb8s7+9Ub6yJpP8ORHvl1r0hw5PLYzeZE0Z1R2DWRET80J//EX1r/cogBnh/lgHuNFJn3ltHo0jr96MoATwMlJk2sBnvEKmAtX8LNfyBhsZTo1bBuTttieoJ3XWt6edtpiHvEsoHC4/O9YUUsoYLatgM4DPFv1RVLoQOp8PQI+YB3/tRQdLBenkQyExjKEjUmqU/EZCpJo1nBNcZZ3Q3x1KU3xl2aJg9Dqlq9Igj1TvK1h/eJD56LH7v+ZR2alAIEkU8Cq8K+feeXFFqNV20bhfR8iVfhaq5LJnRF9a28ZYef3ODbjp9uT2y0HsuSNsBLSiSBWOWg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
