env:
  global:
    - secure: NLAB+w0yqDHAGtCfe1OucUG6hACqJENPCRQE7Y/IAz0JTTvAuqBlWUELwxsULAuahQhRi/PvHg3I7lIOWAI2oDVxX8M2lrJZXdaD9IEgzskGD0bSnipJvTMchyfHCIDW4ZDqyZwvahPbFx9kffcRc5vKpFAWM8C+vomUQqXbyoxMUclnjDgjdQTLweAVMXdT1GRT6BAaOoyoBX+LOTnNvqVEpf+ElsPpWzAcRjYBp/xPozcr/YNakTI+dnac6jG8LONk1zxJuZMHS6nUpTbqUvkMgiUb69UhFtSDa+38ZfFZkJgEaucBXw4yxZva+LuOphVN2845lnPFYuaEzECgAqNx/73l/Iqe/t216sKbrANlPg51g+A5oyw3S0cOwiakgoMBymNXvDU6NE+GX98WBO48S30SL9VNn0nAGnMJN5AjyvgnPodWNeEFLfs0Na/oVBOAsgYNh/M1J58WwzQ8BCoozDzOQFgV+QOykQfrmWH7RqPc/5QqekdVzEJpyq2HpWKrvD8XCtLvG9UGBE006tsgANTaT0oD0+0U4k1MaACv5duaMuMoEV429r2zvYaUAQUxVFplsX2dj2rfSLki2GKx0pZj0csRtrt1RBRr9BXWGoal+jMEFHyOKU/0C51YHRCNxsPbkVLm6Y0f2UkKlwazQ9HL5r+Sj37ZKg6kyXI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
