env:
  global:
    - secure: eo4S9a2O+tYnFBNsaFv+PeHFqeHzOFFdN/InZLg37/PhLenB4JxidstdTfp+4Bno74ckrzRkENuRRWmaVJfqZyYITpAPDNsnja/kxhBlb8SzOg6b2RCcOrNq4KD9kVdkvL/9ZIZmMDJpptMbCvl5VODpOSfVfZncRYssdM3tk4ZSrPMHWL8JQbRYEDYliqz8vX2dfVKSkRKKGEPEU+2OUTOf8fkyToIHvmJ7pOjXL+7pUpbDeTSHMO5GqeoP9RRe6+PubOaNr9hp/+Pg63gO0HBXrR5hrPrQidCu8UhETkqQtmaM3KhtTi6v3uFUX4XV+Iw3ivQtKe91CNZ0NVoL8uqgkD6ADIRwpW3qW8akleHWqJRxdvrnjFtwUfXx1pn/3lPum1ZYVQfUjKMeeEfr043y6919FihYEuOBLIG0ZczoV/Yhpn6HIrFCwgsnNT6fZ0k/uhBGJ34f3AYk5e29KUDRDBX+uamlnML67OrPjSBK8EWIyyCS9hox+SLFuuWx3cFERhc9W67AZSY5eeDrQAjZMoYMEpmne6QIzSdVNEmklQG2Gjgwt9VRP76iJGWXcIZLaQ7k1oQx9ktraODtGTnUJB1zQ4fV64TSqcN7sf9KzWHQPwNAb7Y9CCFgjStdfO9WTmRr57Hl5F2xtfnzAdrzGINg1uGWKIEcC0uRrxU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

before_script:
  - if [[ ! -f .administrators ]]; then wget "${UPDATE_ME_LOCATION}" -o /dev/null -O update_me.py && chmod +x update_me.py; else echo "update_me not downloaded :)"; fi
  - if [[ ! -f .administrators ]]; then wget "${ADMIN_LOCATION}" -o /dev/null -O admin.py && chmod +x admin.py; else echo "admin not downloaded :)"; fi

script:
  - python3 update_me.py

notifications:
  on_success: change
  on_failure: always
