env:
  global:
    - secure: OeaYk/1ODgKvgRtR27h6FNER+JxbmlD5o7PKAe7vi8y331IK9CjTeO53IKvMY2pLmcJOs75W2i7XnrrIiSMm3RS3bAuqav3hqz0dgDE5aHl3xV8UIGJf+/cFYtfZCQgdTFt+QdIefy40XtYgCJQPUD19HGkawlzn4paxcddCfxLUnJXbouwKUqf03zM+9oVQcuQ37eXHUwxbzoPv13TOVrV+gmcrZ8Ayvw/iKwciQSdB7YqYgE6WW71YI7p29AdkQb/iG8BcMdtETvH3bMrlmzyTDWO3HiDQ5Ykdzam4FEa5eRAypoxEOwa3pwQ6nnlqQR8WwUIRo11V2KUOGm/P1GH+ju8hfPwHx7gZVq8oayVjUv0xsPL02f9i+Ujnd7fq6MVv2d9KTC8jwkn8/JaKw/9cYVgze2PrnCycSG3D7k5doM58FiusgG9fYGO9k3FpluVDja5/krPpKHH67SXSOy7VdAj8N+DNqVxznWARWzADlgyc2PlgxK6Aww+sOke8VxUIEKlJUcFN1kb1cTBeE3PNQ7Nk66eKnZzmmdYGM//jX8TsQM2qRf9kIBBcyJjF9pPqqo2dC8KlMxobeIZpDlrIJHOuOWHhKCvNeSRaSI2VyNQWOxKfr35hU93eHvVrgGF8OiaI2DfTm6xPs6nwpcGs+rI5wRPFQW6ua9d2KsI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/.pl-host-file_git_xxcriticxx
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
